### ISSUE TITLE
[PE-D] Using max int as index will result in confusing invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-4/tp#163]
doing `display 1000` will result in an error message stating that `The index provided is invalid` which is fair enough because the number of contacts in the app does not reach 1000.

However, doing `display 2147483648` does not result in that previous error message stated above. Instead, it shows an invalid command format error which is confusing because the format of the command matches the format of the error message shown:

![image.png](https://raw.githubusercontent.com/aryagiat/ped/main/files/a4530652-8194-471e-9ee2-4d7e51e8bfbd.png)

Similar with other commands which containts `COUNT` like `filter`.
Doing `filter gender 2147483648` will result in a misleading error message which is confusing:
![image.png](https://raw.githubusercontent.com/aryagiat/ped/main/files/5fa67757-d821-496f-9487-b1f9f16e01c1.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: aryagiat/ped#9

**Comment by Kangxun** [comment]
fixed for filter
