### ISSUE TITLE
[PE-D] Exporting CSV

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-4/tp#164]
Bug Report:
- When I tried to export data, it only exported the contact that I added and not the sample data along with it.

Screenshot:

![Screenshot 2021-10-29 at 4.48.14 PM.png](https://raw.githubusercontent.com/reddevil1313/ped/main/files/2e12d013-3586-423d-9107-72675c1c4c75.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: reddevil1313/ped#11

**Comment by idgrr** [comment]
This could be the case of opening the wrong csv file based on confusing csv name

**Comment by idgrr** [comment]
Could not recreate the bug. 

1. added person
2. set as done
3. export

When exporting, shows how many left in address book. If it does contain other people, it should export together.
