### ISSUE TITLE
[PE-D] Information window still shows the information of the contact after running the clear command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-4/tp#165]
How to reproduce:
1. Run the CMM.jar program
2. Enter the 'clear' command
3. The information window still contains the information of the previously shown contact (see screenshot 3.1)

**Screenshot 3.1:**
![image.png](https://raw.githubusercontent.com/WangGLJoseph/ped/main/files/1010dd01-58f1-404b-b4c2-91b789eebaee.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: WangGLJoseph/ped#3

**Comment by houtenteo** [comment]
FIX THIS @loose-bus-change
