### ISSUE TITLE
[PE-D] `Start New Using Import` bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T13-4/tp#171]
After using the `clear` command to clear all contacts from the CMM database, I exited the app using the `exit` command. I selected don't export since there are 0 people in the addressbook. However, when i restart the application and select the `Start New Using Import` button, the app starts with 0 contacts loaded. Is this supposed to happen? Based on the UG, I interpret the  `Start New Using Import` button as I will not be importing any contacts and instead i will start with the default contacts.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: El0hime/ped#1

**Comment by idgrr** [comment]
Not  a bug, wrong csv file was given to testers
